project_id = "ezbpvgfubzdxxwbqqcsm"

[functions.create-initial-admin]
verify_jwt = false

[functions.create-teacher]
verify_jwt = false

[functions.create-student]
verify_jwt = false

[functions.send-demo-confirmation]
verify_jwt = false

[functions.send-demo-request]
verify_jwt = false

[functions.submit-demo-request]
verify_jwt = false

[functions.generate-worksheet]
verify_jwt = true

[functions.generate-diagram-spec]
verify_jwt = true

[functions.generate-notes]
verify_jwt = true

[functions.generate-quiz]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.get-quiz-for-student]
verify_jwt = false

[functions.submit-quiz]
verify_jwt = false

[functions.start-quiz-attempt]
verify_jwt = false

[functions.go-to-question]
verify_jwt = false

[functions.save-answer]
verify_jwt = false
